### ISSUE TITLE
5V GND y BAT

### ISSUE THREAD

**Issue by danybd** [garabullo/garabullo2018#41]
Hola,
una duda que tengo con respecto a los paths +5V GND y bat. Cual es su funcion? Se tiene que soldar algun 7805? O simplemente una bateria y usar el regulador lineal del arduino?

Saludos!

**Comment by DiegoLale** [comment]
Hola. La salida del step-up de + va a 5v y la - a gnd. (Despues de regular
el step up). A mayores saca un cable del positivo de la batería a bat. Está
conectado a una entrada analógica para monitorizar el nivel de carga de
batería.
Saludos

**Comment by danybd** [comment]
Hola Diego. Y cual es la tension maxima que puede tener la batería? Porque entiendo que la monitorización se hace directamente sobre un canal ADC del arduino. Esta pensado para una LIPO? Dos pilas AA?
Saludos

**Comment by DiegoLale** [comment]
Una lipo, como máximo 4.2 aprox.
Está aquí el sistema:
https://github.com/garabullo/garabullo2018/wiki/2--Alimentación

**Comment by danybd** [comment]
Gracias!!!
