### ISSUE TITLE
Junta torica ruedas

### ISSUE THREAD

**Issue by danybd** [garabullo/garabullo2018#45]
Hola,
quería preguntarte cual es la medida de las juntas tóricas que llevan las ruedas, pues he comprado unas de 63-65mm y le quedan enormes. Cuales le has montado tú?

Gracias

**Comment by DiegoLale** [comment]
Hola, hay varias medidas que pueden valer. de unos 38-40mm son las que uso yo. De 2mm o 2.5mm de diámetro. Un saludo.
