### ISSUE TITLE
Cargar firmware

### ISSUE THREAD

**Issue by Fendetestas72** [garabullo/garabullo2018#46]
Buenas, pues como dice el título, soy incapaz de cargar el firmware. Me pone que es demasiado grande para el Arduino Nano.
Necesito ayudaaaaaaaaa!!!!!!!!
Gracias.

**Comment by DiegoLale** [comment]
Perdón, he estado muy ausente, el problema es que con las últimas versiones de las librerías, éstas ocupan más espacio, este fin de semana cuelgo un firmware aligerado para evitar ese problema, y perdón por la demora.

**Comment by Fendetestas72** [comment]
Ok Diego, muchas gracias.

**Comment by DiegoLale** [comment]
Listo, acabo de subir la versión "GARABULLO18_1.0".
Con arduino 1.8.10 y las librerías actualizadas a día de hoy ya funciona.
Ya me cuentas si sirve

**Comment by Fendetestas72** [comment]
Pues parece que no va, o por lo menos a mi, me sale esto
El Sketch usa 30828 bytes (100%) del espacio de almacenamiento de programa. El máximo es 30720 bytes.
Las variables Globales usan 921 bytes (44%) de la memoria dinámica, dejando 1127 bytes para las variables locales. El máximo es 2048 bytes.

**Comment by DiegoLale** [comment]
Dime que sistema operativo, versión de arduino y versión de las librerías tienes:
Adafruit_GFX.h
Adafruit_ST7735.h
Adafruit_NeoPixel.h

**Comment by Fendetestas72** [comment]
Todo correcto, tenía las librerías sin actualizar, ahora va perfecto, gracias y perdona por dar la brasa, si vas por la OSHWDEM, te invito a una birra.

**Comment by DiegoLale** [comment]
Perfecto, mejor así. Este año no toca, nos vemos en la siguiente.
